
# Notes from Word Doc -----------------------------------------------------

# Check things with tar_make() in the console to make sure the pipeline is 
# working

# tar_validate(): Warnings about R versions are ok, if things look good (i.e. 
# no errors), you can run tar_make()

# Use the following in the console to take a “look” at the workflow:
# tar_visnetwork()

# tar_load() retrieves targets that have been created in the past (stored in 
# the _targets folder that use_targets()|tar_make() creates)

# tar_glimpse(): looks at the target objects that have been created

# tar_load()/tar_read() can both be used to retrieve specific plots/tar objects

# tar_invalidate(): if you want to rerun a specific step that targets has
# already done and thinks is finished, run this on it. You can check if it 
# needs to be updated again, or if any other step is out of date, by using
# tar_outdated(). Just run tar_make() again to rerun the system.

# tar_destroy(): deletes all or part of the data generated by tar_make()/etc.